-- MySQL Script generated by MySQL Workbench
-- Tue Apr 22 21:24:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL DEFAULT NULL,
  `adm` TINYINT NULL DEFAULT FALSE,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Localidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Localidade` (
  `id_localidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_localidade`));


-- -----------------------------------------------------
-- Table `mydb`.`Prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prato` (
  `id_prato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `foto` VARCHAR(255) NULL DEFAULT NULL,
  `id_localidade` INT NULL DEFAULT NULL,
  `criado_por` INT NOT NULL,
  PRIMARY KEY (`id_prato`),
  INDEX (`criado_por` ASC) VISIBLE,
  INDEX (`id_localidade` ASC) VISIBLE,
    FOREIGN KEY (`criado_por`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`),
    FOREIGN KEY (`id_localidade`)
    REFERENCES `mydb`.`Localidade` (`id_localidade`));


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_prato` INT NOT NULL,
  `texto` TEXT NOT NULL,
  `data_comentario` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_comentario`),
  INDEX `idx_comentario_prato` (`id_prato` ASC) VISIBLE,
  INDEX (`id_usuario` ASC) VISIBLE,
  INDEX (`id_prato` ASC) VISIBLE,
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`),
    FOREIGN KEY (`id_prato`)
    REFERENCES `mydb`.`Prato` (`id_prato`));


-- -----------------------------------------------------
-- Table `mydb`.`Reacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reacao` (
  `id_reacao` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_prato` INT NOT NULL,
  `tipo` ENUM('like', 'deslike') NOT NULL,
  `data_reacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_reacao`),
  UNIQUE INDEX (`id_usuario` ASC, `id_prato` ASC) VISIBLE,
  INDEX `idx_reacao_prato` (`id_prato` ASC) VISIBLE,
  INDEX (`id_usuario` ASC) VISIBLE,
  INDEX (`id_prato` ASC) VISIBLE,
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`),
    FOREIGN KEY (`id_prato`)
    REFERENCES `mydb`.`Prato` (`id_prato`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


DELETE FROM Usuario WHERE email = 'luiz@sabordobrasil.com';
INSERT INTO usuario(nome, email, senha, adm) VALUES ('Administrador Luiz', 'luiz@sabordobrasil.com', 'l123456', 1);
